apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: agent
  name: agent
  namespace: nonprod
spec:
  ports:
    - name: "5520"
      port: 5520
      targetPort: 5520
  selector:
    io.kompose.service: agent
status:
  loadBalancer: {}
