apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
  namespace: nonprod
spec:
  ports:
    - name: "5510"
      port: 5510
      targetPort: 5510
  type: LoadBalancer
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
