apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
  namespace: nonprod
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: keycloak
status:
  loadBalancer: {}
