apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web-client
  name: web-client
  namespace: nonprod
spec:
  ports:
    - name: "5500"
      port: 5500
      targetPort: 5500
  selector:
    io.kompose.service: web-client
  type: LoadBalancer
status:
  loadBalancer: {}
