apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../api/docker-compose.yml -o generated
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: wss
  name: wss
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wss
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../api/docker-compose.yml -o generated
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: wss
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis://redis
            - name: REDIS_PASSWORD
              value: REconDIS
            - name: VALID_ORIGINS
              value: http://localhost:3001
          image: quay.io/reconmap/ws-server:latest
          name: rmap-wss
          ports:
            - containerPort: 8765
          resources: {}
      restartPolicy: Always
status: {}
