apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconmap-web-frontend-deployment
spec:
  selector:
    matchLabels:
      app: reconmap-web-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: reconmap-web-frontend
    spec:
      containers:
        - name: reconmap-web-frontend
          image: reconmap/web-frontend:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always

