kind: Service
apiVersion: v1
metadata:
  name: reconmap-web-frontend-np
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30001
  selector:
    app: reconmap-web-frontend

